version: '3'

services:
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules

  backend:
    build: ./backend
    ports:
      - "1337:1337"
    volumes:
      - ./backend:/app
      - /app/node_modules
    depends_on:
      - frontend
